title: ByteMe
author:
  email: 'info@byteme.in'
description: Where knowledge is shared

plugins:
  - jekyll-feed
  - jekyll-remote-theme

remote_theme: jonaharagon/jekyll-bootstrap-theme
# Theme configuration information: https://github.com/jonaharagon/jekyll-bootstrap-theme

excerpts:
  show: true
  auto_truncate: true

bootstrap:
  social_links:
    github:  'https://github.com/akshob/byteme.in'